name: Check LGTM label

on:
  pull_request_target:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check lgtm label
        uses: actions/github-script@v6
        if: ${{!(contains(github.event.pull_request.labels.*.name, 'lgtm') || contains(github.event.pull_request.labels.*.name, 'workflow'))}}
        with:
          script: |
            throw 'Code review required - please add the "lgtm" label if build scripts satisfies the Package Styling Manual.';
